### ISSUE TITLE
Filters missing in the built package

### ISSUE THREAD

**Issue by kdesineedi** [cqsupport/webinar-dispatchercache#6]
Hi @andrewmkhoury 

Thanks for the code and we were planning to customize this code for our needs.

We observed that the package built by checking out the code does not have any filters in the generated package and due to this we could not uninstall the package.
 
Kindly let us know if this was intended or we can fix this in any way?

**Comment by andrewmkhoury** [comment]
Not intentional, it is old and intended as only sample code.  Go ahead and copy the code itself to your project.

**Comment by kdesineedi** [comment]
Thanks. Closing the issue.
